repos:
  - repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
      - id: black
        language_version: python3.8
  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
      - id: poetry-check
      - id: poetry-lock