version: '3'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=...
    volumes:
      - ...:/var/lib/postgresql/data  # Specify local path to PostgreSQL data folder
    restart: always
  melting_potlist:
    depends_on:
      - db
    build: .
    expose:
      - 8000
    environment:
      - VIRTUAL_HOST=melting-potlist.domain.com
      - LETSENCRYPT_HOST=melting-potlist.domain.com
    volumes:
      - ...:/usr/src/app/melting_potlist.yaml   # Specify local path to the config file (use melting_potlist.example.yaml as starting point)

networks:
  default:
    external:
      name: nginx-proxy