version: '3'

services:
  db:
    image: postgres:11
    environment:
      - POSTGRES_PASSWORD=...
    volumes:
      - ...:/var/lib/postgresql/data
    restart: always
  melting_potlist:
    depends_on:
      - db
    build: .
    expose:
      - 8000
    environment:
      - VIRTUAL_HOST=melting-potlist.domain.com
      - LETSENCRYPT_HOST=melting-potlist.domain.com

networks:
  default:
    external:
      name: nginx-proxy