# Generated by Django 3.1 on 2020-09-30 23:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user_profile', '0003_migrate_previous_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='core_playlist_url',
        ),
    ]
