# Generated by Django 3.2.9 on 2021-12-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0006_add_dynamic_playlists_and_track_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackuri",
            name="unavailable",
            field=models.BooleanField(default=False),
        ),
    ]
