# Generated by Django 4.0 on 2022-09-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("user_profile", "0012_alter_dynamicplaylist_tracks_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertrack",
            name="listeners",
        ),
        migrations.AddField(
            model_name="dynamicplaylisttrack",
            name="user",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="auth.user"),
        ),
        migrations.DeleteModel(
            name="UserTrackListenStats",
        ),
    ]
